Models/Payment.cs
using System;

namespace MovieTickets.Models
{
    public class Payment
    {

        public int PaymentID { get; set; }

        public int BookingID { get; set; }

        public double Amount { get; set; }

        public DateTime PaymentTime { get; set; }
        public string Userid { get; set; }
        public string username { get; set; }

        public bool IsPaid { get; set; }

        public string PaymentMethod { get; set; }

        // Navigate properity
        public Booking Booking { get; set; } = null!;
    }
}

Controllers/PaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieTickets.Models;
using MovieTickets.Services;
using Stripe;
using System;

namespace MovieTickets.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
       static MovieOrder orders;


        decimal mony;
        private readonly IMovieOrderRepository movieorderService;
        private readonly IMovieRepository movieservice;

        public PaymentController(IMovieOrderRepository movieorderService,IMovieRepository movieservice)
        {
            this.movieorderService = movieorderService;
            this.movieservice = movieservice;
        }
       

        public IActionResult Index(Movie movie)
        {
            
          orders  = new MovieOrder();
            orders.UserId = HttpContext.Session.GetString("id");
            orders.Movie = movieservice.GetById(movie.Id); 


            return View(orders);
        }



        [HttpPost]
        public IActionResult Processing(MovieOrder order,string stripeToken, string stripeEmail)
        {
          MovieOrder o=new MovieOrder()
          {
              MovieId =order.Movie.Id,
              UserId=order.UserId,
              Quantity =order.Quantity,

          };

            mony = (decimal)(order.Quantity * orders.Movie.Price);

            var optionsCust = new CustomerCreateOptions
            {
                Email = stripeEmail,
                Name = "Robert",
                Phone = "04-234567",
                

            };
            var serviceCust = new CustomerService();
            Customer customer = serviceCust.Create(optionsCust);
            var optionsCharge = new ChargeCreateOptions
            {
                /*Amount = HttpContext.Session.GetLong("Amount")*/
                Amount = Convert.ToInt64(mony),
                Currency = "USD",
                Description = "Buying Flowers",
                Source = stripeToken,
                ReceiptEmail = stripeEmail,

            };
            var service = new ChargeService();
            Charge charge = service.Create(optionsCharge);
            if (charge.Status == "succeeded")
            {
                movieorderService.insert(o);   
                string BalanceTransactionId = charge.BalanceTransactionId;
                ViewBag.AmountPaid = Convert.ToDecimal(charge.Amount)  ;
                ViewBag.BalanceTxId = BalanceTransactionId;
                ViewBag.Customer = customer.Name;
                return RedirectToAction("Index","Cart");
            }

            return View();
        }



    }
}

Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTickets.Models;

namespace MovieTickets.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly PadelContext _context;

        public PaymentsController(PadelContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var padelContext = _context.Payments.Include(p => p.Booking);
            return View(await padelContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Booking)
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create(int bookingId)
        {
            ViewData["BookingID"] = new SelectList(_context.Bookings, "BookingID", "BookingID");
            var userName = User.Identity.Name; // Get the username of the authenticated user
            ViewBag.Username = userName;
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentID,BookingID,Amount,PaymentTime,IsPaid,PaymentMethod")] Payment payment)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userName = User.Identity.Name;
            if (payment!=null)
            {
                payment.Userid = userId;
                payment.username = userName;
              

                var booking = await _context.Bookings.FindAsync(payment.BookingID);
                if (booking != null)
                {
                    payment.Amount = booking.TotalAmount;
                    payment.PaymentTime = DateTime.Now;
                    payment.IsPaid = true; // Assuming payment is successful

                    _context.Add(payment);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("PaymentSuccess");
                }
                ModelState.AddModelError("", "Selected booking not found.");
            }
            ViewData["BookingID"] = new SelectList(_context.Bookings, "BookingID", "BookingID", payment.BookingID);
            return View(payment);
        }
        public IActionResult PaymentSuccess()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetBookingAmount(int bookingId)
        {
            var booking = await _context.Bookings.FindAsync(bookingId);
            if (booking != null)
            {
                return Json(new { amount = booking.TotalAmount });
            }
            return NotFound();
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            ViewData["BookingID"] = new SelectList(_context.Bookings, "BookingID", "BookingID", payment.BookingID);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentID,BookingID,Amount,PaymentTime,IsPaid,PaymentMethod")] Payment payment)
        {
            if (id != payment.PaymentID)
            {
                return NotFound();
            }

            if (payment != null)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookingID"] = new SelectList(_context.Bookings, "BookingID", "BookingID", payment.BookingID);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Booking)
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.FindAsync(id);
            if (payment != null)
            {
                _context.Payments.Remove(payment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
            return _context.Payments.Any(e => e.PaymentID == id);
        }
    }
}

Views/Payments/Create.cshtml
@model MovieTickets.Models.Payment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="Username">User Name</label>
                <input type="text" class="form-control" id="Username" value="@ViewBag.Username" readonly />
            </div>


            <div class="form-group">
                <label asp-for="BookingID" class="control-label">Booking</label>
                <select asp-for="BookingID" class="form-control" asp-items="ViewBag.BookingID" id="bookingSelect">
                    <option value="" selected>Select a booking</option>
                </select>
                <span asp-validation-for="BookingID" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label for="amount">Amount</label>
                <input type="text" id="amount" class="form-control" readonly />
            </div>


            <div class="form-group">
                <label asp-for="PaymentMethod" class="control-label"></label>
                <select asp-for="PaymentMethod" class="form-control">
                    <option value="">Select Payment Method</option>
                    <option value="Card">Card</option>
                    <option value="Vodafone Cash">Vodafone Cash</option>
                    <option value="InstaPay">InstaPay</option>
                    <option value="Cash">Cash</option>
                </select>
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            function fetchAmount() {
                var bookingId = $('#bookingSelect').val();
                if (bookingId) {
                    $.ajax({
                        url: '@Url.Action("GetBookingAmount", "Payments")',
                        type: 'GET',
                        data: { bookingId: bookingId },
                        success: function (data) {
                            $('#amount').val(data.amount);
                        },
                        error: function () {
                            alert('An error occurred while fetching the amount.');
                        }
                    });
                } else {
                    $('#amount').val('');
                }
            }

            // Trigger on change
            $('#bookingSelect').change(fetchAmount);

            // Trigger immediately if a booking is already selected
            fetchAmount();
        });
    </script>
}

Views/Payments/Delete.cshtml
@model MovieTickets.Models.Payment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPaid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentMethod)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Booking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Booking.BookingID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PaymentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Payments/Details.cshtml
@model MovieTickets.Models.Payment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPaid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentMethod)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Booking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Booking.BookingID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PaymentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Payments/Edit.cshtml
@model MovieTickets.Models.Payment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaymentID" />
            <div class="form-group">
                <label asp-for="BookingID" class="control-label"></label>
                <select asp-for="BookingID" class="form-control" asp-items="ViewBag.BookingID"></select>
                <span asp-validation-for="BookingID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentTime" class="control-label"></label>
                <input asp-for="PaymentTime" class="form-control" />
                <span asp-validation-for="PaymentTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPaid" /> @Html.DisplayNameFor(model => model.IsPaid)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PaymentMethod" class="control-label"></label>
                <input asp-for="PaymentMethod" class="form-control" />
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/Index.cshtml
@model IEnumerable<MovieTickets.Models.Payment>

@{
    ViewData["Title"] = "Index";
}
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <h1>Payments DashBoard</h1>
    <br />

    @* <p>
    <a asp-action="Create">Create New</a>
</p> *@
    <table class="table table-hover table-striped">
        <thead>
            <tr>

                <th>
                    Booking ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.username)
                </th>


                <th>
                    @Html.DisplayNameFor(model => model.PaymentTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsPaid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaymentMethod)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking.BookingID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking.username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsPaid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentMethod)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.PaymentID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.PaymentID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.PaymentID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

Views/Payments/PaymentSuccess.cshtml
<div class="row">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Your Payment was created successfully</h2>
        <p>You Will Be Directed in 10 seconds to <a asp-controller="Home1" asp-action="Index">Home</a> page</p>
        <hr />
        <p>Thank you!</p>
    </div>
</div>

<script>
    setTimeout(function () {
        window.location.href = '/Home1/index';
    }, 10000);
</script>