Models/Cinema.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTickets.Models
{
    public class Cinema
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Location { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public virtual List<MovieInCinema> MoviesInCinema { get; set; }
    }
}

Controllers/CinemaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieTickets.Models;
using MovieTickets.Services;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MovieTickets.ViewModels;

namespace MovieTickets.Controllers
{
    public class CinemaController : Controller
    {
        ICinemaRepository cinemaRepo;
        MovieContext db;
        private readonly IMovieInCinemaRepository movieInCinemaService;
        #region Constructor Injection
        public CinemaController(ICinemaRepository _cinemaRepo, MovieContext _db,IMovieInCinemaRepository movieInCinemaService)
        {
            cinemaRepo = _cinemaRepo;
            db = _db;
            this.movieInCinemaService = movieInCinemaService;
        }
        #endregion
 
        #region User
        #region Index
        public IActionResult Index()
        {
            List<Cinema> cinemas = cinemaRepo.GetAll();
            return View("AllCinemas", cinemas);
        }
        #endregion
        #region Details
        public IActionResult Cinema(int id)
        {
            MovieCinemaViewModel cinema = new MovieCinemaViewModel()
            {
                Cinema = cinemaRepo.GetById(id),
                Movies = movieInCinemaService.GetAll().Where(w => w.Cinema.Id == id).ToList(),
            };

            return View("CinemaUserDetails", cinema);
        }
        #endregion
        #endregion

        #region Admin
        #region Index
        [Authorize(Roles = "Admin")]
        public IActionResult AdminCinemas()
        {
            List<Cinema> cinemas = cinemaRepo.GetAll();
            return View("AdminCinemas", cinemas);
        }
        #endregion
        #region Details
        [Authorize(Roles = "Admin")]
        public IActionResult CinemaDetailsAdmin(int id)
        {
            Cinema cinema = cinemaRepo.GetById(id);
            return View("CinemaDetailsAdmin", cinema);
        }
        #endregion
        #region Insert
        #region Get
        [Authorize(Roles = "Admin")]
        public IActionResult InsertForm()
        {

            return View("Cinema_Insert_Form", new Cinema());
        }


        #endregion
        #region Post
        [Authorize(Roles = "Admin")]
        public IActionResult InsertCinema(Cinema InsertCinema, List<IFormFile> Image)
        {
            if (ModelState.IsValid)
            {
                cinemaRepo.insert(InsertCinema, Image);
                return RedirectToAction("AdminCinemas");
            }
            return RedirectToAction("InsertForm", InsertCinema);
            //Retrun to Details
        }
        #endregion

        #endregion
        #region Update

        #region Get
        public IActionResult UpdateForm(int id)
        {

            Cinema cinema = cinemaRepo.GetById(id);
            return View("CinemaUpdateForm", cinema);
        }


        #endregion
        #region Post
        [Authorize(Roles = "Admin")]
        public IActionResult UpdateCinema(Cinema EditCin, int id, List<IFormFile> Image)
        {
            if (ModelState.IsValid)
            {
                cinemaRepo.update(EditCin, id, Image);
                return RedirectToAction("AdminCinemas");
            }
            return View("CinemaUpdateForm", EditCin);//Retrun to Details
        }
        #endregion

        #endregion

        #region Delete
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            cinemaRepo.delete(id);
            return RedirectToAction("AdminCinemas");
        }
        #endregion

        #endregion
        #region Search
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminCinemas(string Keyword)
        {
            ViewData["searching"] = Keyword;
            var cinemas = db.Cinemas.Select(x => x);
            if (!string.IsNullOrEmpty(Keyword))
            {
                cinemas = cinemas.Where(c => c.Name.Contains(Keyword) || c.Location.Contains(Keyword));

            }
            return View(await cinemas.AsNoTracking().ToListAsync());
        }
        #endregion

        #region GetCinemaByNmae
        public IActionResult CinemaName(string name)
        {
            Cinema cinema = cinemaRepo.GetByName(name);
            return View(cinema);
        }
        #endregion
        #region GetcinemaByLocation
        public IActionResult CinemaLocation(string location)
        {
            Cinema cinema = cinemaRepo.GetByLocation(location);
            return View(cinema);
        }
        #endregion
       
    }
}

Views/Cinema/AdminCinemas.cshtml
@model List<Cinema>

@{
    Layout = "_AdminLayout";
}



@*Admin Section Start------------------------------------------------------*@

<div class="search-box pull-left mb-5">
                            <form asp-action="AdminCinemas" asp-controller="Cinema" method = "get">
                                <input type="search" value=@ViewData["searching"] name="Keyword" placeholder="Search for Cinemas..." >
                                <i class="ti-search"></i>
                                <input type="submit" style="display: none" />
                            </form>
                        </div>
<div class="container mt-5">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
	  @foreach(var i in Model){
    <tr>
      <th scope="row">@i.Id</th>
      <td>@i.Name</td>
      <td>@i.Location</td>
      <td>@i.Description</td>
      <td> <a asp-action="UpdateForm" asp-route-id = "@i.Id"> <i class="fa fa-edit"></i></a> <a asp-action="Delete" asp-route-id = "@i.Id"> <i class="ti-trash"></i></a> <a asp-action="CinemaDetailsAdmin" asp-route-id = "@i.Id"><i class="fa fa-arrow-circle-right"></i></a></td>

    </tr>
	  }
  </tbody>
</table>
@if(Model.Count == 0)
{
    <img src="/images/error/notfound.png" style="height:50vh; text-align:center; margin-left:30%;" />
    <a asp-action="InsertForm" class="btn btn-warning font-weight-bold" style=" color: white; width:70px; height:70px; border-radius:50%; text-align:center; padding: 2.5% 0;"> Add  <i class="fa fa-plus-circle"></i></a>

}
    @if(Model.Count != 0)
    {
        <a asp-action="InsertForm" class="btn btn-primary"> Add  <i class="fa fa-plus-circle"></i></a>  
    }
</div>
@*Admin Section end -----------------------------------------*@

Views/Cinema/AllCinemas.cshtml
@model List<Cinema>


@*User Section start----------------------------------------*@
@{
    Layout = "_UserLayout";
}
<div class="slider movie-items">
	<div class="container">
	<div class="container">
		<div class="row ipad-width">
<div class="col-md-12">
				
				<div class="title-hd">
					<h2>OUR CINEMAS</h2>
				</div>
				<div class="tabs">
					
				    <div class="tab-content">
				        
				        <div id="tab22" class="tab active">
				           <div class="row">
				            	<div class="slick-multiItem h-100">
									@foreach(var i in Model)
										{
											<div class="slide-it">
	
												<div class="movie-item">

													<div class="mv-img">
														@if (i.Image != null)
														{
															var base64 = Convert.ToBase64String(@i.Image);
															var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

															<img src="@imgSrc" alt="" style="width:inherit; height:50vh">
														}
													</div>
					            			<div class="hvr-inner">
					            				<a  asp-action="Cinema" asp-route-id=@i.Id asp-controller="Cinema"> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6 class="text-light" style="color:white;">@i.Name</h6>
					            			
					            			</div>
					            		</div>
				            			
				            		</div>
										}
				            	</div>
				            </div>
			       	 	</div>
				    </div>
				</div>
			</div>
			</div>
			</div>
			</div>
			</div>
@*User Section end---------------------------------------------------------*@

Views/Cinema/CinemaDetailsAdmin.cshtml
@model Cinema

@{
    Layout = "_AdminLayout";
}
<div class="container mt-5 " style="margin-left:20%">
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
        @{
		    var base64 = Convert.ToBase64String(@Model.Image);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
		}
      <img src="@imgSrc">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
      </div>
    </div>
  </div>
</div>
</div>

Views/Cinema/CinemaUpdateForm.cshtml
@model Cinema

@{
    Layout = "_AdminLayout";
}

<div class="container mt-5">
<form asp-action = "UpdateCinema" asp-controller= "Cinema" asp-route-id="@Model.Id" class="w-50 m-auto" method= "post" enctype= "multipart/form-data" >
 <div class="container">
   <div class="picture-container">
      <div class="picture">
            @*image proplem ===================================================================*@
                    @if(Model.Image == null)
                    {
                        <img src = "/images/placeholder.jfif" class="picture-src" style="height: 100%;" id="ProfileImg">
                        
                    }
            @if(Model.Image != null){
                var base64 = Convert.ToBase64String(Model.Image);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

          <img src = "@imgSrc" class="picture-src" style="height: 100%;" id="ProfileImg">
            }
          <input asp-for="Image" accept="image/*" type="file" class="picfile" id="fileInput" onchange="loadFile(event)">
                     @*<input type="file" asp-for="Image" id="Image" onchange="readURL(this);" />*@
          @*image proplem =========================================================================*@

       </div>
       </div>
 </div>
    <div>

        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" >
    </div>
    <div>
        <label asp-for="Location"></label>
        <input class="form-control" asp-for="Location">
    </div>
      <div>
        <label asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
    </div>
   
 
      <div class="d-flex justify-content-between mt-3">
        <input type= "submit" value = "Update" class="btn btn-success ps-5 pe-5"  />
        <a asp-action="AdminCinemas" class="btn btn-danger ">Cancel</a>

    </div>

</form>
</div>

<script>
    var loadFile = function (event) {
  var image = document.getElementById("ProfileImg");
  image.src = URL.createObjectURL(event.target.files[0]);
};
</script>
<style>
.picture-container{
    margin:auto;
    width:100px;
    height:100px;
    border-radius: 50%;
}
.picture{
    position:relative;
    width:100px;
    height:100px;
    border-radius: 50%;
}
.picture-src{
    position:absolute;
    width: inherit;
    height:inherit;
    border-radius:inherit;
}
.picture input[type="file"] {
    cursor: pointer;
    display: block;
    height: 100%;
    left: 0;
    opacity: 0 !important;
    position: absolute;
    top: 0;
    width: 100%;
}
</style>

Views/Cinema/CinemaUserDetails.cshtml
@model MovieCinemaViewModel

@{
    Layout="_UserLayout";
}
<div class="hero hero3">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- <h1> movie listing - list</h1>
				<ul class="breadcumb">
					<li class="active"><a href="#">Home</a></li>
					<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>
<!-- celebrity single section-->

<div class="page-single movie-single cebleb-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="mv-ceb">
					
						@if(Model.Cinema.Image!=null){
							var base64=	Convert.ToBase64String(@Model.Cinema.Image);
               string imgsrc= string.Format("data:images/*;base64,{0}", base64);
					<img src="@imgsrc" alt="" style="width:350px; height:500px; object-fit:cover">
					}
				</div>
			</div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="movie-single-ct">
					<h1 class="bd-hd">@Model.Cinema.Name</h1>
					<p class="ceb-single" >@Model.Cinema.Description </p>
					<div class="social-link cebsingle-socail" hidden>
						<br />
						<br />
					</div>
					<div class="movie-tabs">
						<div class="tabs">
							<div class="tabs">
							<ul class="tab-links tabs-mv">
								<li class="active"><a href="#overviewceb">Overview</a></li>
								                      
							</ul>
						    <div class="tab-content">
						        <div id="overviewceb" class="tab active">
						            <div class="row">
						            	<div class="col-md-8 col-sm-12 col-xs-12">
						            	
						            	
											<!-- movie cast -->
											<div class="mvcast-item">	
												@foreach(var item in Model.Movies){
												
												<div class="cast-it">
													<div class="cast-left cebleb-film">
														
															@if(item.Movie.Image!=null) {
																var base64=	Convert.ToBase64String(@item.Movie.Image);
                                              string  imgsrc= string.Format("data:images/*;base64,{0}", base64);
														<img src="@imgsrc"  style="width:120px; height:90px; object-fit:cover">
															}
														<div>
															<a asp-action="details" asp-controller="movie" asp-route-id="@item.Movie.Id">@item.Movie.Name </a>
														
														</div>
														
													</div>
													
												</div>
												}
											</div>
						            	</div>
						            
						            </div>

						    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>

Views/Cinema/Cinema_Insert_Form.cshtml
@model Cinema

@{
    Layout = "_AdminLayout";
}

<div class="container mt-5">
<form asp-action = "InsertCinema" asp-controller= "Cinema" class="w-50 m-auto" method= "post" enctype= "multipart/form-data" >
    <div class="container">
   <div class="picture-container">
      <div class="picture">
            @*image proplem ===================================================================*@
                    @if(Model.Image == null)
                    {
                        <img src = "/images/placeholder.jfif" class="picture-src" style="height: 100%;" id="ProfileImg">
                        
                    }
            @if(Model.Image != null){
                var base64 = Convert.ToBase64String(Model.Image);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

          <img src = "@imgSrc" class="picture-src" style="height: 100%;" id="ProfileImg">
            }
          <input asp-for="Image" accept="image/*" type="file" class="picfile" id="fileInput" onchange="loadFile(event)">
                     @*<input type="file" asp-for="Image" id="Image" onchange="readURL(this);" />*@
          @*image proplem =========================================================================*@

       </div>
       </div>
 </div>
    <div>

        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" >
    </div>
    <div>
        <label asp-for="Location"></label>
        <input class="form-control" asp-for="Location">
    </div>
      <div>
        <label asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
    </div>
   
 
      <div class="d-flex justify-content-between mt-3">
        <input type= "submit" value = "Insert" class="btn btn-success ps-5 pe-5"  />
        <a asp-action="AdminCinemas" class="btn btn-danger ">Cancel</a>

    </div>

</form>
</div>

<script>
    var loadFile = function (event) {
  var image = document.getElementById("ProfileImg");
  image.src = URL.createObjectURL(event.target.files[0]);
};
</script>
<style>
.picture-container{
    margin:auto;
    width:100px;
    height:100px;
    border-radius: 50%;
}
.picture{
    position:relative;
    width:100px;
    height:100px;
    border-radius: 50%;
}
.picture-src{
    position:absolute;
    width: inherit;
    height:inherit;
    border-radius:inherit;
}
.picture input[type="file"] {
    cursor: pointer;
    display: block;
    height: 100%;
    left: 0;
    opacity: 0 !important;
    position: absolute;
    top: 0;
    width: 100%;
}
</style>